name: Selenium Test

on:
  push:
    branches:
      - main

jobs:

  test-dung:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Login Dung
        run: mvn test -Dtest=LoginTest#loginDung

  test-sai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Login Sai
        run: mvn test -Dtest=LoginTest#loginSai